# Generated by Django 4.0 on 2023-11-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ingrediente_alter_receita_options_categoria_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icon',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoriaingrediente'),
        ),
    ]
