# Generated by Django 4.0 on 2023-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoriaingrediente_remove_categoria_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredients',
            field=models.ManyToManyField(through='app.ReceitaIngrediente', to='app.Ingrediente'),
        ),
    ]
