# Generated by Django 4.0 on 2023-11-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Planificacao',
        ),
    ]
